/* ZAMBOANGUITA.FDB collection analysis queries
   Read-only SELECT statements only.
   Parameters used:
     :date_from  -- inclusive date, e.g. DATE '2026-01-01'
     :date_to    -- inclusive date, e.g. DATE '2026-01-31'

   Notes:
   - PAYMENT is the payment/receipt header.
   - PAYMENTDETAIL is the line-level revenue/fund detail.
   - PAYMENTCLASSDETAIL is especially useful for RPT class/tax-year breakdowns.
   - Receipt number is PAYMENT.RECEIPTNO.
   - Void/cancelled filters are written defensively; confirm local status codes before production use.
*/

/* 1. Unified collection detail: RPT, CTC, and Other Fees/Charges */
SELECT
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END AS PROCESS_NAME,
    p.PAYMENT_ID,
    p.RECEIPTNO,
    p.PAYMENTDATE,
    p.VALUEDATE,
    p.LOCAL_TIN,
    tp.OWNERNAME,
    p.PAIDBY,
    p.COLLECTOR,
    p.USERID,
    p.RCDNUMBER,
    p.ORB_ID,
    p.PAYGROUP_CT,
    p.PAYMODE_CT,
    pm.DESCRIPTION AS PAYMODE_DESCRIPTION,
    p.STATUS_CT,
    st.DESCRIPTION AS STATUS_DESCRIPTION,
    pd.PAYMENTDETAIL_ID,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    pd.FUNDTYPE_CT,
    ft.DESCRIPTION AS FUNDTYPE_DESCRIPTION,
    pd.SOURCE_CT,
    pd.SOURCEID,
    pd.DEBITPOSTINGID,
    pd.AMOUNTPAID,
    p.AMOUNT AS PAYMENT_HEADER_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN TAXPAYER tp ON tp.LOCAL_TIN = p.LOCAL_TIN
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
LEFT JOIN T_FUNDTYPE ft ON ft.CODE = pd.FUNDTYPE_CT
LEFT JOIN T_PAYMODE pm ON pm.CODE = p.PAYMODE_CT
LEFT JOIN T_STATUS st ON st.CODE = p.STATUS_CT
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
ORDER BY p.PAYMENTDATE, p.RECEIPTNO, pd.RECEIPTITEMORDER, pd.PAYMENTDETAIL_ID;

/* 2. Real Property Tax payment detail with RPT posting/account context */
SELECT
    p.PAYMENT_ID,
    p.RECEIPTNO,
    p.PAYMENTDATE,
    p.LOCAL_TIN,
    tp.OWNERNAME,
    p.PAIDBY,
    p.COLLECTOR,
    pd.PAYMENTDETAIL_ID,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    pd.FUNDTYPE_CT,
    pd.AMOUNTPAID,
    pd.DEBITPOSTINGID,
    tpa.TAXTRANS_ID,
    tpa.PROP_ID,
    tpa.TAXYEAR,
    tpa.TAXPERIOD_CT,
    tpa.CASETYPE_CT,
    tpa.EARMARK_CT,
    tpa.EVENTOBJECT_CT,
    pcd.CLASSCODE_CT,
    pcd.PROPERTYKIND_CT,
    pcd.ACTUALUSE_CT,
    pcd.TAXYEAR AS CLASS_TAXYEAR,
    pcd.AMOUNT AS CLASS_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN PAYMENTCLASSDETAIL pcd
       ON pcd.PAYMENT_ID = p.PAYMENT_ID
      AND pcd.ITAXTYPE_CT = pd.ITAXTYPE_CT
LEFT JOIN TPACCOUNT tpa ON tpa.POSTING_ID = pd.DEBITPOSTINGID
LEFT JOIN TAXPAYER tp ON tp.LOCAL_TIN = p.LOCAL_TIN
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
WHERE p.PAYGROUP_CT = 'RPT'
  AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
ORDER BY p.PAYMENTDATE, p.RECEIPTNO, tpa.TAXYEAR, pd.ITAXTYPE_CT;

/* 3. RPT totals by Basic/SEF/other RPT line classification */
SELECT
    CAST(p.PAYMENTDATE AS DATE) AS COLLECTION_DATE,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    pd.FUNDTYPE_CT,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
WHERE p.PAYGROUP_CT = 'RPT'
  AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY CAST(p.PAYMENTDATE AS DATE), pd.ITAXTYPE_CT, it.DESCRIPTION, pd.FUNDTYPE_CT
ORDER BY COLLECTION_DATE, pd.ITAXTYPE_CT;

/* 4. Community Tax Certificate / Cedula payment detail */
SELECT
    p.PAYMENT_ID,
    p.RECEIPTNO,
    p.PAYMENTDATE,
    p.LOCAL_TIN,
    tp.OWNERNAME,
    p.PAIDBY,
    p.COLLECTOR,
    pd.PAYMENTDETAIL_ID,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    pd.SOURCE_CT,
    pd.SOURCEID,
    pd.AMOUNTPAID,
    ctc.CTC_ID,
    ctc.CTCNO,
    ctc.DATEISSUED,
    ctc.CTCTYPE,
    ctc.CTCYEAR,
    ctc.BASICTAXDUE,
    ctc.BUSTAXDUE,
    ctc.SALTAXDUE,
    ctc.RPTAXDUE,
    ctc.INTEREST,
    ctc.TOTALAMOUNTPAID
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN COMMUNITYTAXCERTIFICATE ctc
       ON ctc.CTC_ID = pd.SOURCEID
      AND pd.SOURCE_CT IN ('CTCI', 'CTCC')
LEFT JOIN TAXPAYER tp ON tp.LOCAL_TIN = p.LOCAL_TIN
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
WHERE (pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC')
  AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
ORDER BY p.PAYMENTDATE, p.RECEIPTNO, ctc.CTCNO;

/* 5. CTC totals; compares payment line totals to CTC computed/recorded totals */
SELECT
    CAST(p.PAYMENTDATE AS DATE) AS COLLECTION_DATE,
    ctc.CTCTYPE,
    ctc.CTCYEAR,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    COUNT(DISTINCT ctc.CTC_ID) AS CTC_COUNT,
    SUM(pd.AMOUNTPAID) AS PAYMENTDETAIL_TOTAL,
    SUM(ctc.TOTALAMOUNTPAID) AS CTC_RECORDED_TOTAL,
    SUM(
        COALESCE(ctc.BASICTAXDUE, 0)
      + COALESCE(ctc.BUSTAXDUE, 0)
      + COALESCE(ctc.SALTAXDUE, 0)
      + COALESCE(ctc.RPTAXDUE, 0)
      + COALESCE(ctc.INTEREST, 0)
    ) AS CTC_COMPONENT_TOTAL
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN COMMUNITYTAXCERTIFICATE ctc
       ON ctc.CTC_ID = pd.SOURCEID
      AND pd.SOURCE_CT IN ('CTCI', 'CTCC')
WHERE (pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC')
  AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY CAST(p.PAYMENTDATE AS DATE), ctc.CTCTYPE, ctc.CTCYEAR
ORDER BY COLLECTION_DATE, ctc.CTCTYPE, ctc.CTCYEAR;

/* 6. Other Fees and Charges payment detail */
SELECT
    p.PAYMENT_ID,
    p.RECEIPTNO,
    p.PAYMENTDATE,
    p.LOCAL_TIN,
    tp.OWNERNAME,
    p.PAIDBY,
    p.COLLECTOR,
    p.PAYGROUP_CT,
    pd.PAYMENTDETAIL_ID,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    pd.FUNDTYPE_CT,
    ft.DESCRIPTION AS FUNDTYPE_DESCRIPTION,
    pd.SOURCE_CT,
    pd.SOURCEID,
    pd.UNIT,
    pd.AMOUNTPAID
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN TAXPAYER tp ON tp.LOCAL_TIN = p.LOCAL_TIN
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
LEFT JOIN T_FUNDTYPE ft ON ft.CODE = pd.FUNDTYPE_CT
WHERE COALESCE(p.PAYGROUP_CT, '') <> 'RPT'
  AND NOT (pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC')
  AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
ORDER BY p.PAYMENTDATE, p.RECEIPTNO, pd.RECEIPTITEMORDER, pd.ITAXTYPE_CT;

/* 7. Other Fees and Charges totals by revenue code */
SELECT
    CAST(p.PAYMENTDATE AS DATE) AS COLLECTION_DATE,
    p.PAYGROUP_CT,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    pd.FUNDTYPE_CT,
    ft.DESCRIPTION AS FUNDTYPE_DESCRIPTION,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
LEFT JOIN T_FUNDTYPE ft ON ft.CODE = pd.FUNDTYPE_CT
WHERE COALESCE(p.PAYGROUP_CT, '') <> 'RPT'
  AND NOT (pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC')
  AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY CAST(p.PAYMENTDATE AS DATE), p.PAYGROUP_CT,
         pd.ITAXTYPE_CT, it.DESCRIPTION, pd.FUNDTYPE_CT, ft.DESCRIPTION
ORDER BY COLLECTION_DATE, p.PAYGROUP_CT, pd.ITAXTYPE_CT;

/* 8. Daily collections for the three processes */
SELECT
    CAST(p.PAYMENTDATE AS DATE) AS COLLECTION_DATE,
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END AS PROCESS_NAME,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY CAST(p.PAYMENTDATE AS DATE),
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END
ORDER BY COLLECTION_DATE, PROCESS_NAME;

/* 9. Monthly collections for the three processes */
SELECT
    EXTRACT(YEAR FROM p.PAYMENTDATE) AS COLLECTION_YEAR,
    EXTRACT(MONTH FROM p.PAYMENTDATE) AS COLLECTION_MONTH,
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END AS PROCESS_NAME,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY EXTRACT(YEAR FROM p.PAYMENTDATE),
         EXTRACT(MONTH FROM p.PAYMENTDATE),
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END
ORDER BY COLLECTION_YEAR, COLLECTION_MONTH, PROCESS_NAME;

/* 10. Quarterly collections for the three processes */
SELECT
    EXTRACT(YEAR FROM p.PAYMENTDATE) AS COLLECTION_YEAR,
    CAST(((EXTRACT(MONTH FROM p.PAYMENTDATE) - 1) / 3) + 1 AS INTEGER) AS COLLECTION_QUARTER,
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END AS PROCESS_NAME,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY EXTRACT(YEAR FROM p.PAYMENTDATE),
         CAST(((EXTRACT(MONTH FROM p.PAYMENTDATE) - 1) / 3) + 1 AS INTEGER),
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END
ORDER BY COLLECTION_YEAR, COLLECTION_QUARTER, PROCESS_NAME;

/* 11. Yearly collections for the three processes */
SELECT
    EXTRACT(YEAR FROM p.PAYMENTDATE) AS COLLECTION_YEAR,
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END AS PROCESS_NAME,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY EXTRACT(YEAR FROM p.PAYMENTDATE),
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END
ORDER BY COLLECTION_YEAR, PROCESS_NAME;

/* 12. Receipt range and header-vs-detail reconciliation */
SELECT
    CAST(p.PAYMENTDATE AS DATE) AS COLLECTION_DATE,
    p.RECEIPTNO,
    p.PAYMENT_ID,
    p.PAYGROUP_CT,
    p.PAIDBY,
    p.AMOUNT AS HEADER_AMOUNT,
    SUM(pd.AMOUNTPAID) AS DETAIL_AMOUNT,
    p.AMOUNT - SUM(pd.AMOUNTPAID) AS DIFFERENCE_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
GROUP BY CAST(p.PAYMENTDATE AS DATE), p.RECEIPTNO, p.PAYMENT_ID,
         p.PAYGROUP_CT, p.PAIDBY, p.AMOUNT
ORDER BY COLLECTION_DATE, p.RECEIPTNO;

/* 13. Other Fees and Charges tax/rate list */
SELECT
    opr.OPRATE_ID,
    opr.ITAXTYPE_CT,
    it.DESCRIPTION AS ITAXTYPE_DESCRIPTION,
    opr.OPGROUP,
    opr.OPSUBGROUP,
    opr.DESCRIPTION AS RATE_DESCRIPTION,
    opr.RATE,
    opr.YEARSTART,
    opr.VALIDFROM,
    opr.ORDINANCENO,
    opr.MUNICIPAL_ID,
    opr.EDITABLERATE_BV,
    it.FUNDTYPE_CT,
    ft.DESCRIPTION AS FUNDTYPE_DESCRIPTION,
    it.BLGF_CODE,
    it.COA_CODE
FROM T_OTHERPAYMENTRATE opr
LEFT JOIN T_ITAXTYPE it ON it.CODE = opr.ITAXTYPE_CT
LEFT JOIN T_FUNDTYPE ft ON ft.CODE = it.FUNDTYPE_CT
WHERE (opr.VALIDFROM IS NULL OR opr.VALIDFROM < DATEADD(1 DAY TO CAST(:date_to AS DATE)))
  AND (opr.YEARSTART IS NULL OR opr.YEARSTART <= EXTRACT(YEAR FROM CAST(:date_to AS DATE)))
ORDER BY opr.ITAXTYPE_CT, opr.OPGROUP, opr.OPSUBGROUP, opr.DESCRIPTION, opr.YEARSTART;

/* 14. Other Fees and Charges parent-child hierarchy with rates */
SELECT
    lvl1.CODE AS LEVEL1_CODE,
    lvl1.DESCRIPTION AS LEVEL1_DESCRIPTION,
    lvl2.CODE AS LEVEL2_CODE,
    lvl2.DESCRIPTION AS LEVEL2_DESCRIPTION,
    lvl3.CODE AS LEVEL3_CODE,
    lvl3.DESCRIPTION AS LEVEL3_DESCRIPTION,
    lvl4.CODE AS LEVEL4_CODE,
    lvl4.DESCRIPTION AS LEVEL4_DESCRIPTION,
    lvl5.CODE AS LEVEL5_CODE,
    lvl5.DESCRIPTION AS LEVEL5_DESCRIPTION,
    child.CODE AS CHARGE_CODE,
    child.DESCRIPTION AS CHARGE_DESCRIPTION,
    child.PARENTCODE AS CHARGE_PARENT_CODE,
    child.TREELEVEL AS CHARGE_TREELEVEL,
    child.FUNDTYPE_CT,
    ft.DESCRIPTION AS FUNDTYPE_DESCRIPTION,
    child.BLGF_CODE,
    child.COA_CODE,
    opr.OPRATE_ID,
    opr.OPGROUP,
    opr.OPSUBGROUP,
    opr.DESCRIPTION AS RATE_DESCRIPTION,
    opr.RATE,
    opr.YEARSTART,
    opr.VALIDFROM,
    opr.ORDINANCENO,
    opr.MUNICIPAL_ID,
    opr.EDITABLERATE_BV
FROM T_ITAXTYPE child
LEFT JOIN T_ITAXTYPE lvl5 ON lvl5.CODE = child.PARENTCODE
LEFT JOIN T_ITAXTYPE lvl4 ON lvl4.CODE = lvl5.PARENTCODE
LEFT JOIN T_ITAXTYPE lvl3 ON lvl3.CODE = lvl4.PARENTCODE
LEFT JOIN T_ITAXTYPE lvl2 ON lvl2.CODE = lvl3.PARENTCODE
LEFT JOIN T_ITAXTYPE lvl1 ON lvl1.CODE = lvl2.PARENTCODE
LEFT JOIN T_FUNDTYPE ft ON ft.CODE = child.FUNDTYPE_CT
LEFT JOIN T_OTHERPAYMENTRATE opr ON opr.ITAXTYPE_CT = child.CODE
WHERE child.CODE NOT IN ('RPT', 'BSC', 'SEF', 'CTC')
  AND (
        child.CODE IN (SELECT DISTINCT ITAXTYPE_CT FROM T_OTHERPAYMENTRATE WHERE ITAXTYPE_CT IS NOT NULL)
        OR child.CODE IN (
            SELECT DISTINCT pd.ITAXTYPE_CT
            FROM PAYMENT p
            JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
            WHERE COALESCE(p.PAYGROUP_CT, '') <> 'RPT'
              AND NOT (pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC')
              AND p.PAYMENTDATE >= CAST(:date_from AS DATE)
              AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
              AND COALESCE(p.VOID_BV, 0) = 0
        )
      )
  AND (opr.OPRATE_ID IS NULL
       OR (
            (opr.VALIDFROM IS NULL OR opr.VALIDFROM < DATEADD(1 DAY TO CAST(:date_to AS DATE)))
            AND (opr.YEARSTART IS NULL OR opr.YEARSTART <= EXTRACT(YEAR FROM CAST(:date_to AS DATE)))
          ))
ORDER BY
    COALESCE(lvl1.CODE, ''),
    COALESCE(lvl2.CODE, ''),
    COALESCE(lvl3.CODE, ''),
    COALESCE(lvl4.CODE, ''),
    COALESCE(lvl5.CODE, ''),
    child.CODE,
    opr.OPGROUP,
    opr.OPSUBGROUP,
    opr.DESCRIPTION;

/* 15. Total collection per collector: daily, monthly, and yearly */
SELECT
    x.PERIOD_TYPE,
    x.COLLECTION_YEAR,
    x.COLLECTION_MONTH,
    x.COLLECTION_DATE,
    x.COLLECTOR,
    x.USERID,
    x.RECEIPT_COUNT,
    x.TOTAL_AMOUNT
FROM (
    SELECT
        'DAILY' AS PERIOD_TYPE,
        EXTRACT(YEAR FROM p.PAYMENTDATE) AS COLLECTION_YEAR,
        EXTRACT(MONTH FROM p.PAYMENTDATE) AS COLLECTION_MONTH,
        CAST(p.PAYMENTDATE AS DATE) AS COLLECTION_DATE,
        COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED') AS COLLECTOR,
        p.USERID,
        COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
        SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT,
        1 AS SORT_ORDER
    FROM PAYMENT p
    JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
    WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
      AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
      AND COALESCE(p.VOID_BV, 0) = 0
    GROUP BY
        EXTRACT(YEAR FROM p.PAYMENTDATE),
        EXTRACT(MONTH FROM p.PAYMENTDATE),
        CAST(p.PAYMENTDATE AS DATE),
        COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED'),
        p.USERID

    UNION ALL

    SELECT
        'MONTHLY' AS PERIOD_TYPE,
        EXTRACT(YEAR FROM p.PAYMENTDATE) AS COLLECTION_YEAR,
        EXTRACT(MONTH FROM p.PAYMENTDATE) AS COLLECTION_MONTH,
        CAST(NULL AS DATE) AS COLLECTION_DATE,
        COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED') AS COLLECTOR,
        p.USERID,
        COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
        SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT,
        2 AS SORT_ORDER
    FROM PAYMENT p
    JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
    WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
      AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
      AND COALESCE(p.VOID_BV, 0) = 0
    GROUP BY
        EXTRACT(YEAR FROM p.PAYMENTDATE),
        EXTRACT(MONTH FROM p.PAYMENTDATE),
        COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED'),
        p.USERID

    UNION ALL

    SELECT
        'YEARLY' AS PERIOD_TYPE,
        EXTRACT(YEAR FROM p.PAYMENTDATE) AS COLLECTION_YEAR,
        CAST(NULL AS INTEGER) AS COLLECTION_MONTH,
        CAST(NULL AS DATE) AS COLLECTION_DATE,
        COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED') AS COLLECTOR,
        p.USERID,
        COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
        SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT,
        3 AS SORT_ORDER
    FROM PAYMENT p
    JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
    WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
      AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
      AND COALESCE(p.VOID_BV, 0) = 0
    GROUP BY
        EXTRACT(YEAR FROM p.PAYMENTDATE),
        COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED'),
        p.USERID
) x
ORDER BY
    x.SORT_ORDER,
    x.COLLECTION_YEAR,
    x.COLLECTION_MONTH,
    x.COLLECTION_DATE,
    x.COLLECTOR,
    x.USERID;

/* 16. Fees collected by selected collector */
SELECT
    COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED') AS COLLECTOR,
    p.USERID,
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END AS PROCESS_NAME,
    p.PAYGROUP_CT,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION AS FEE_DESCRIPTION,
    pd.FUNDTYPE_CT,
    ft.DESCRIPTION AS FUNDTYPE_DESCRIPTION,
    pd.SOURCE_CT,
    COUNT(DISTINCT p.PAYMENT_ID) AS RECEIPT_COUNT,
    MIN(p.RECEIPTNO) AS FIRST_RECEIPTNO,
    MAX(p.RECEIPTNO) AS LAST_RECEIPTNO,
    MIN(CAST(p.PAYMENTDATE AS DATE)) AS FIRST_PAYMENT_DATE,
    MAX(CAST(p.PAYMENTDATE AS DATE)) AS LAST_PAYMENT_DATE,
    SUM(pd.AMOUNTPAID) AS TOTAL_AMOUNT
FROM PAYMENT p
JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
LEFT JOIN T_ITAXTYPE it ON it.CODE = pd.ITAXTYPE_CT
LEFT JOIN T_FUNDTYPE ft ON ft.CODE = pd.FUNDTYPE_CT
WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
  AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
  AND COALESCE(p.VOID_BV, 0) = 0
  AND (
        :collector IS NULL
        OR UPPER(TRIM(p.COLLECTOR)) = UPPER(TRIM(:collector))
        OR UPPER(TRIM(p.USERID)) = UPPER(TRIM(:collector))
      )
GROUP BY
    COALESCE(NULLIF(TRIM(p.COLLECTOR), ''), TRIM(p.USERID), 'UNSPECIFIED'),
    p.USERID,
    CASE
        WHEN p.PAYGROUP_CT = 'RPT' THEN 'REAL_PROPERTY_TAX'
        WHEN pd.SOURCE_CT IN ('CTCI', 'CTCC') OR pd.ITAXTYPE_CT = 'CTC' THEN 'COMMUNITY_TAX'
        ELSE 'OTHER_FEES_CHARGES'
    END,
    p.PAYGROUP_CT,
    pd.ITAXTYPE_CT,
    it.DESCRIPTION,
    pd.FUNDTYPE_CT,
    ft.DESCRIPTION,
    pd.SOURCE_CT
ORDER BY
    COLLECTOR,
    PROCESS_NAME,
    pd.ITAXTYPE_CT,
    pd.SOURCE_CT;

/* 17. Sources of Collections summary */
WITH source_map AS (
    SELECT 1 AS SOURCE_ORDER, 'Manufacturing' AS SOURCE_NAME, 'MAS' AS ITAXTYPE_CT FROM RDB$DATABASE
    UNION ALL SELECT 2, 'Distributor', 'WHO' FROM RDB$DATABASE
    UNION ALL SELECT 3, 'Retailing', 'RET' FROM RDB$DATABASE
    UNION ALL SELECT 4, 'Banks & Other Financial Int.', 'BFI' FROM RDB$DATABASE
    UNION ALL SELECT 5, 'Other Business Tax', 'OBT' FROM RDB$DATABASE
    UNION ALL SELECT 6, 'Sand & Gravel', 'TSG' FROM RDB$DATABASE
    UNION ALL SELECT 6, 'Sand & Gravel', 'TSB' FROM RDB$DATABASE
    UNION ALL SELECT 7, 'Fines & Penalties', 'FPT' FROM RDB$DATABASE
    UNION ALL SELECT 7, 'Fines & Penalties', 'FPF' FROM RDB$DATABASE
    UNION ALL SELECT 7, 'Fines & Penalties', 'FPO' FROM RDB$DATABASE
    UNION ALL SELECT 7, 'Fines & Penalties', 'FPS' FROM RDB$DATABASE
    UNION ALL SELECT 7, 'Fines & Penalties', 'FPE' FROM RDB$DATABASE
    UNION ALL SELECT 8, 'Mayor''s Permit', 'MP' FROM RDB$DATABASE
    UNION ALL SELECT 9, 'Weight & Measure', 'FWM' FROM RDB$DATABASE
    UNION ALL SELECT 10, 'Tricycle Permit Fee', 'TOP' FROM RDB$DATABASE
    UNION ALL SELECT 10, 'Tricycle Permit Fee', 'MTO' FROM RDB$DATABASE
    UNION ALL SELECT 11, 'Occupation Tax', 'OCC' FROM RDB$DATABASE
    UNION ALL SELECT 12, 'Cert. of Ownership', 'COO' FROM RDB$DATABASE
    UNION ALL SELECT 13, 'Cert. of Transfer', 'COT' FROM RDB$DATABASE
    UNION ALL SELECT 14, 'Cockpit Share', 'CS' FROM RDB$DATABASE
    UNION ALL SELECT 15, 'Docking and Mooring Fee', NULL FROM RDB$DATABASE
    UNION ALL SELECT 16, 'Sultadas', 'ST' FROM RDB$DATABASE
    UNION ALL SELECT 17, 'Miscellaneous', 'IM' FROM RDB$DATABASE
    UNION ALL SELECT 18, 'Registration of Birth', 'RB' FROM RDB$DATABASE
    UNION ALL SELECT 19, 'Marriage Fee', 'RM' FROM RDB$DATABASE
    UNION ALL SELECT 20, 'Burial Fee', 'BF' FROM RDB$DATABASE
    UNION ALL SELECT 21, 'Correction of Entry', 'CE' FROM RDB$DATABASE
    UNION ALL SELECT 22, 'Fishing Permit Fee', 'FRF' FROM RDB$DATABASE
    UNION ALL SELECT 22, 'Fishing Permit Fee', 'IF' FROM RDB$DATABASE
    UNION ALL SELECT 23, 'Sale of Agri. Prod.', 'IAP' FROM RDB$DATABASE
    UNION ALL SELECT 24, 'Sale of Acct. Forms', 'IAF' FROM RDB$DATABASE
    UNION ALL SELECT 25, 'Water Fee', 'WTR' FROM RDB$DATABASE
    UNION ALL SELECT 25, 'Water Fee', 'IWO' FROM RDB$DATABASE
    UNION ALL SELECT 26, 'Market Stall Fee', 'RFM' FROM RDB$DATABASE
    UNION ALL SELECT 26, 'Market Stall Fee', 'MSF' FROM RDB$DATABASE
    UNION ALL SELECT 27, 'Cash Tickets', NULL FROM RDB$DATABASE
    UNION ALL SELECT 28, 'SlaughterHouse Fee', 'SPF' FROM RDB$DATABASE
    UNION ALL SELECT 28, 'SlaughterHouse Fee', 'RFS' FROM RDB$DATABASE
    UNION ALL SELECT 29, 'Rental of Equipment', 'RFR' FROM RDB$DATABASE
    UNION ALL SELECT 30, 'Doc Stamp Tax', NULL FROM RDB$DATABASE
    UNION ALL SELECT 31, 'Police Clearance', 'PCL' FROM RDB$DATABASE
    UNION ALL SELECT 32, 'Secretaries Fees', 'SF' FROM RDB$DATABASE
    UNION ALL SELECT 33, 'Med./Lab. Fees', 'MDL' FROM RDB$DATABASE
    UNION ALL SELECT 34, 'Garbage Fees', 'GCF' FROM RDB$DATABASE
    UNION ALL SELECT 35, 'Cutting Tree', NULL FROM RDB$DATABASE
    UNION ALL SELECT 36, 'Com Tax Cert.', 'CTC' FROM RDB$DATABASE
    UNION ALL SELECT 37, 'Building Permit Fee', 'PFB' FROM RDB$DATABASE
    UNION ALL SELECT 37, 'Building Permit Fee', 'BUF' FROM RDB$DATABASE
    UNION ALL SELECT 38, 'Electrical Permit Fee', 'EP' FROM RDB$DATABASE
    UNION ALL SELECT 39, 'Zoning Fee', 'ZLC' FROM RDB$DATABASE
    UNION ALL SELECT 40, 'Livestock', 'IFL' FROM RDB$DATABASE
    UNION ALL SELECT 41, 'Diving Fee', 'IFD' FROM RDB$DATABASE
),
valid_details AS (
    SELECT
        p.PAYMENT_ID,
        p.RECEIPTNO,
        p.PAYMENTDATE,
        p.COLLECTOR,
        p.USERID,
        pd.ITAXTYPE_CT,
        pd.AMOUNTPAID
    FROM PAYMENT p
    JOIN PAYMENTDETAIL pd ON pd.PAYMENT_ID = p.PAYMENT_ID
    WHERE p.PAYMENTDATE >= CAST(:date_from AS DATE)
      AND p.PAYMENTDATE < DATEADD(1 DAY TO CAST(:date_to AS DATE))
      AND COALESCE(p.VOID_BV, 0) = 0
      AND (
            :collector IS NULL
            OR UPPER(TRIM(p.COLLECTOR)) = UPPER(TRIM(:collector))
            OR UPPER(TRIM(p.USERID)) = UPPER(TRIM(:collector))
          )
)
SELECT
    sm.SOURCE_ORDER,
    sm.SOURCE_NAME,
    LIST(DISTINCT sm.ITAXTYPE_CT, ', ') AS MAPPED_ITAXTYPE_CODES,
    COUNT(DISTINCT vd.PAYMENT_ID) AS RECEIPT_COUNT,
    MIN(vd.RECEIPTNO) AS FIRST_RECEIPTNO,
    MAX(vd.RECEIPTNO) AS LAST_RECEIPTNO,
    MIN(CAST(vd.PAYMENTDATE AS DATE)) AS FIRST_PAYMENT_DATE,
    MAX(CAST(vd.PAYMENTDATE AS DATE)) AS LAST_PAYMENT_DATE,
    SUM(COALESCE(vd.AMOUNTPAID, 0)) AS TOTAL_AMOUNT
FROM source_map sm
LEFT JOIN valid_details vd ON vd.ITAXTYPE_CT = sm.ITAXTYPE_CT
GROUP BY sm.SOURCE_ORDER, sm.SOURCE_NAME
ORDER BY sm.SOURCE_ORDER;

/* 18. Process flow: Real Property Tax payment */
SELECT *
FROM (
SELECT 1 AS STEP_NO, 'Identify property and taxpayer account' AS PROCESS_STEP,
       'PROPERTY, PROPERTYOWNER, PROPERTYOWNERDETAIL, TAXPAYER, RPTLIABILITY' AS TABLES_INVOLVED,
       'PROP_ID, PINNO, LOCAL_TIN, ADMINLOCAL_TIN, OWNERNAME, OWNERADDRESS, PROPERTYKIND_CT, BARANGAY_CT, MUNICIPAL_ID' AS IMPORTANT_FIELDS,
       'The RPT process starts by locating the real property record and taxpayer/administrator responsible for the liability.' AS WHAT_HAPPENS
FROM RDB$DATABASE
UNION ALL SELECT 2, 'Identify tax declaration / assessment',
       'RPTASSESSMENT, RPTASSESSMENTDETAIL',
       'TAXTRANS_ID, PROP_ID, TDNO, STARTYEAR, STARTQUARTER, ENDYEAR, ENDQUARTER, TAXABILITY_BV, GRYEAR, CLASSCODE_CT, ACTUALUSE_CT, ASSESSEDVALUE',
       'The active tax declaration and assessment detail determine taxability, classification, assessed value, and the period covered by the assessment.'
FROM RDB$DATABASE
UNION ALL SELECT 3, 'Read appraisal / valuation support',
       'RPTLANDAPPRAISAL, RPTBLDGINFO, RPTBLDGFLOOR, RPTMACHAPPRAISAL, RPTPLANTTREEAPPRAISAL, RPTVALUEADJUSTMENT',
       'TAXTRANS_ID, MARKETVALUE, ASSESSEDVALUE, CLASSLEVEL_CT, ACTUALUSE_CT, ADJUSTMENT fields',
       'Supporting RPT appraisal tables explain how assessed values were built for land, building, machinery, plants/trees, and value adjustments.'
FROM RDB$DATABASE
UNION ALL SELECT 4, 'Generate or review RPT debit/liability',
       'POSTINGJOURNAL, MANUALDEBIT',
       'POSTINGJOURNAL_ID, MANUALDEBIT_ID, TAXTRANS_ID, PROP_ID, LOCAL_TIN, TAXYEAR, TDNO, PINNO, RPTTAXDUE, SEFTAXDUE, CANCELLED_BV, POSTED_BV',
       'Debit rows represent collectible RPT amounts by property, tax declaration, and tax year. Manual debits can also hold encoded RPT liabilities.'
FROM RDB$DATABASE
UNION ALL SELECT 5, 'Post debit to taxpayer/property account',
       'TPACCOUNT, POSTINGJOURNAL',
       'POSTING_ID, REFPOSTINGID, TAXTRANS_ID, PROP_ID, LOCAL_TIN, TAXYEAR, ITAXTYPE_CT, DEBITAMOUNT, CREDITAMOUNT, EARMARK_CT, EVENTOBJECT_CT, PK_EVENTOBJECT',
       'PROC_RPTDEBITPOSTING reads unposted POSTINGJOURNAL rows, creates TPACCOUNT debit rows for BSC and SEF, then marks POSTINGJOURNAL.POSTED_BV = 1.'
FROM RDB$DATABASE
UNION ALL SELECT 6, 'Compute amount to be paid',
       'TPACCOUNT, T_TAXPERIOD, T_PENALTYINTERESTPARAM, T_DISCOUNT',
       'TAXYEAR, TAXPERIOD_CT, ITAXTYPE_CT, DEBITAMOUNT, CREDITAMOUNT, VALUEDATE, CASETYPE_CT, EARMARK_CT',
       'Collectible amount is based on account debit/credit balances, tax year, period, case type, penalties, interest, discounts, and Basic/SEF classification.'
FROM RDB$DATABASE
UNION ALL SELECT 7, 'Create official receipt header',
       'PAYMENT',
       'PAYMENT_ID, RECEIPTNO, PAYMENTDATE, VALUEDATE, LOCAL_TIN, PAIDBY, AMOUNT, PAYGROUP_CT, PAYMODE_CT, STATUS_CT, VOID_BV, ORB_ID, RCDNUMBER, COLLECTOR, USERID',
       'Cashier creates one PAYMENT row per official receipt. RPT payments are identified primarily by PAYMENT.PAYGROUP_CT = RPT.'
FROM RDB$DATABASE
UNION ALL SELECT 8, 'Attach OR booklet and RCD references',
       'PAYMENT, RCDORBOOKLET, RCDORBOOKLETINVENTORY, RCDCTRLNUMBER',
       'RECEIPTNO, ORB_ID, RCDNUMBER, AFTYPE, STARTOR, ENDOR, LASTISSUEDOR, BOOKLETNO, COLLECTOR',
       'PAYMENT.RECEIPTNO stores the official receipt number. ORB_ID links to booklet control and RCDNUMBER links to Report of Collections and Deposits.'
FROM RDB$DATABASE
UNION ALL SELECT 9, 'Record RPT payment line items',
       'PAYMENTDETAIL',
       'PAYMENTDETAIL_ID, PAYMENT_ID, DEBITPOSTINGID, ITAXTYPE_CT, FUNDTYPE_CT, SOURCE_CT, SOURCEID, AMOUNTPAID, RECEIPTITEMORDER',
       'Each paid RPT component is stored as a PAYMENTDETAIL row. Basic RPT commonly uses ITAXTYPE_CT = BSC and SEF uses ITAXTYPE_CT = SEF.'
FROM RDB$DATABASE
UNION ALL SELECT 10, 'Allocate by property class / tax year',
       'PAYMENTCLASSDETAIL',
       'PAYCLASSDETAIL_ID, PAYMENT_ID, TAXTRANS_ID, CLASSCODE_CT, PROPERTYKIND_CT, ACTUALUSE_CT, CASETYPE_CT, TAXYEAR, AMOUNT, CANCELLED_BV',
       'This table gives the RPT class, property kind, actual use, case type, and tax-year allocation behind the receipt.'
FROM RDB$DATABASE
UNION ALL SELECT 11, 'Record cheque/payment mode details if needed',
       'PAYMENTCHEQUE, T_PAYMODE, T_BANK',
       'CHEQUE_ID, PAYMENT_ID, BANKCODE, BRANCH, CHECKNUM, AMOUNT, VALUEDATE, CHEQUE_STATUS, PAYMODE_CT',
       'If payment is by cheque or another non-cash mode, supporting payment mode details are stored separately.'
FROM RDB$DATABASE
UNION ALL SELECT 12, 'Classify by fund and revenue account',
       'PAYMENTDETAIL, T_ITAXTYPE, T_FUNDTYPE',
       'ITAXTYPE_CT, FUNDTYPE_CT, DESCRIPTION, BLGF_CODE, COA_CODE, AMOUNTPAID',
       'RPT reporting separates Basic and SEF collections by revenue code and fund classification. Totals should use PAYMENTDETAIL.AMOUNTPAID.'
FROM RDB$DATABASE
UNION ALL SELECT 13, 'Prepare cashier/RCD breakdown',
       'PAYMENT, RCDCTRLNUMBER, RCDORBOOKLET, RCDACCOUNTABLEFORM, RCDCASHBREAKDOWN, RCDFUNDTYPEBREAKDOWN',
       'RCDCTRL_ID, RCDNUMBER, RCDDATE, COLLECTOR, DENOMINATION, QUANTITY, GENERAL_FUND, SEF_FUND, TRUST_FUND, AMOUNT',
       'The cashier/accountable officer summarizes RPT collections in RCD, cash breakdown, fund breakdown, and accountable form records.'
FROM RDB$DATABASE
UNION ALL SELECT 14, 'Deposit / remittance control',
       'RCDDEPOSIT, REMITTANCE, BANKSTATEMENT, BANKSTATEMENTLINE',
       'DEPOSIT_ID, RCDNUMBER, DEPOSITDATE, BANKCODE_CT, AMOUNT, DEPOSIT_SLIP, REMIT_ID',
       'Deposit/remittance tables support reconciliation between reported RPT collections and bank/deposit records.'
FROM RDB$DATABASE
UNION ALL SELECT 15, 'Cancellation, void, and audit checks',
       'PAYMENT, PAYMENTDETAIL, PAYMENTCLASSDETAIL, RPTCANCELLED, RPTCANCELLED_DETAIL, DELETE_AUDITTRAIL, HIS_AUDITTRAIL',
       'VOID_BV, STATUS_CT, CANCELLED_BV, RECEIPTNO, DATALASTEDITED, DELETE audit fields',
       'Reports should exclude voided/cancelled items where appropriate and review audit/delete tables for changed or deleted RPT transactions.'
FROM RDB$DATABASE
UNION ALL SELECT 16, 'Reconcile receipt header vs detail',
       'PAYMENT, PAYMENTDETAIL, PAYMENTCLASSDETAIL, TPACCOUNT',
       'PAYMENT.AMOUNT, SUM(PAYMENTDETAIL.AMOUNTPAID), SUM(PAYMENTCLASSDETAIL.AMOUNT), DEBITPOSTINGID, POSTING_ID',
       'Reconcile the receipt header amount against payment detail totals and class detail allocations. DEBITPOSTINGID should trace back to TPACCOUNT.POSTING_ID.'
FROM RDB$DATABASE
) flow
ORDER BY flow.STEP_NO;

/* 19. Process flow: Community Tax Certificate / Cedula payment */
SELECT *
FROM (
SELECT 1 AS STEP_NO, 'Identify taxpayer / applicant' AS PROCESS_STEP,
       'TAXPAYER, TAXPAYERDETAIL' AS TABLES_INVOLVED,
       'LOCAL_TIN, OWNERNAME, OWNERADDRESS, FIRSTNAME, LASTNAME, DATEOFBIRTH, PLACEOFBIRTH, OCCUPATION, GENDER, CIVILSTATUS, CITIZENSHIP' AS IMPORTANT_FIELDS,
       'The process starts by identifying the individual or entity requesting the Cedula/CTC. Registered payors link through LOCAL_TIN.' AS WHAT_HAPPENS
FROM RDB$DATABASE
UNION ALL SELECT 2, 'Determine CTC type and tax year',
       'COMMUNITYTAXCERTIFICATE',
       'CTCTYPE, CTCYEAR, DATEISSUED, MUNICIPAL_ID, INUSE_BV',
       'The system records whether the certificate is individual/corporate or other local setup type, and the CTC year covered.'
FROM RDB$DATABASE
UNION ALL SELECT 3, 'Resolve CTC rate basis',
       'T_CTCRATE',
       'Rate/code fields, year/effective fields, municipal fields',
       'CTC computation uses the configured Community Tax Certificate rate table. The exact rate fields are held in T_CTCRATE.'
FROM RDB$DATABASE
UNION ALL SELECT 4, 'Compute / encode CTC certificate',
       'COMMUNITYTAXCERTIFICATE, T_CTCRATE',
       'CTC_ID, CTCNO, DATEISSUED, CTCTYPE, CTCYEAR, BASICTAXDUE, BUSTAXDUE, SALTAXDUE, RPTAXDUE, INTEREST, TOTALAMOUNTPAID',
       'The CTC record stores the certificate number and tax components: basic tax, business tax due, salary tax due, real property tax due, interest, and total amount paid.'
FROM RDB$DATABASE
UNION ALL SELECT 5, 'Stamp transaction metadata',
       'COMMUNITYTAXCERTIFICATE',
       'TRANSDATE, USERID, DATALASTEDITED',
       'Trigger TD_CTC sets TRANSDATE to CURRENT_TIMESTAMP when a CTC row is inserted or updated.'
FROM RDB$DATABASE
UNION ALL SELECT 6, 'Create official receipt header',
       'PAYMENT',
       'PAYMENT_ID, RECEIPTNO, PAYMENTDATE, VALUEDATE, LOCAL_TIN, PAIDBY, AMOUNT, PAYMODE_CT, STATUS_CT, VOID_BV, ORB_ID, RCDNUMBER, COLLECTOR, USERID',
       'Cashier creates one PAYMENT row per official receipt. PAYMENT.RECEIPTNO is the official receipt number; it is separate from the CTC certificate number.'
FROM RDB$DATABASE
UNION ALL SELECT 7, 'Attach OR booklet and RCD references',
       'PAYMENT, RCDORBOOKLET, RCDORBOOKLETINVENTORY, RCDCTRLNUMBER',
       'RECEIPTNO, ORB_ID, RCDNUMBER, AFTYPE, STARTOR, ENDOR, LASTISSUEDOR, BOOKLETNO, COLLECTOR',
       'ORB_ID links the receipt to OR booklet control and RCDNUMBER links it to cashier/RCD reporting.'
FROM RDB$DATABASE
UNION ALL SELECT 8, 'Record CTC payment detail',
       'PAYMENTDETAIL',
       'PAYMENTDETAIL_ID, PAYMENT_ID, ITAXTYPE_CT, SOURCE_CT, SOURCEID, FUNDTYPE_CT, AMOUNTPAID, RECEIPTITEMORDER',
       'CTC payment lines are identified by SOURCE_CT values CTCI or CTCC, or by ITAXTYPE_CT = CTC. SOURCEID points to COMMUNITYTAXCERTIFICATE.CTC_ID when SOURCE_CT is CTCI/CTCC.'
FROM RDB$DATABASE
UNION ALL SELECT 9, 'Link receipt line to certificate',
       'PAYMENTDETAIL, COMMUNITYTAXCERTIFICATE',
       'PAYMENTDETAIL.SOURCEID, PAYMENTDETAIL.SOURCE_CT, COMMUNITYTAXCERTIFICATE.CTC_ID, CTCNO',
       'The relationship for certificate tracing is PAYMENTDETAIL.SOURCEID = COMMUNITYTAXCERTIFICATE.CTC_ID for observed CTC source markers.'
FROM RDB$DATABASE
UNION ALL SELECT 10, 'Record cheque/payment mode details if needed',
       'PAYMENTCHEQUE, T_PAYMODE, T_BANK',
       'CHEQUE_ID, PAYMENT_ID, BANKCODE, BRANCH, CHECKNUM, AMOUNT, VALUEDATE, CHEQUE_STATUS, PAYMODE_CT',
       'If payment is by cheque or another non-cash mode, supporting details are stored in PAYMENTCHEQUE.'
FROM RDB$DATABASE
UNION ALL SELECT 11, 'Classify by revenue and fund',
       'PAYMENTDETAIL, T_ITAXTYPE, T_FUNDTYPE',
       'ITAXTYPE_CT, FUNDTYPE_CT, DESCRIPTION, BLGF_CODE, COA_CODE, AMOUNTPAID',
       'CTC reporting should use PAYMENTDETAIL.AMOUNTPAID, with ITAXTYPE_CT = CTC or source markers CTCI/CTCC.'
FROM RDB$DATABASE
UNION ALL SELECT 12, 'Reconcile certificate total vs receipt line total',
       'COMMUNITYTAXCERTIFICATE, PAYMENTDETAIL',
       'TOTALAMOUNTPAID, BASICTAXDUE, BUSTAXDUE, SALTAXDUE, RPTAXDUE, INTEREST, AMOUNTPAID',
       'Cash collection should use PAYMENTDETAIL.AMOUNTPAID; certificate computation can be checked against TOTALAMOUNTPAID and component fields.'
FROM RDB$DATABASE
UNION ALL SELECT 13, 'Prepare cashier/RCD breakdown',
       'PAYMENT, RCDCTRLNUMBER, RCDORBOOKLET, RCDACCOUNTABLEFORM, RCDCASHBREAKDOWN, RCDFUNDTYPEBREAKDOWN',
       'RCDCTRL_ID, RCDNUMBER, RCDDATE, COLLECTOR, DENOMINATION, QUANTITY, GENERAL_FUND, SEF_FUND, TRUST_FUND, AMOUNT',
       'The cashier/accountable officer summarizes CTC collections in RCD, cash breakdown, fund breakdown, and accountable form records.'
FROM RDB$DATABASE
UNION ALL SELECT 14, 'Deposit / remittance control',
       'RCDDEPOSIT, REMITTANCE, BANKSTATEMENT, BANKSTATEMENTLINE',
       'DEPOSIT_ID, RCDNUMBER, DEPOSITDATE, BANKCODE_CT, AMOUNT, DEPOSIT_SLIP, REMIT_ID',
       'Deposit/remittance tables support reconciliation after CTC collections are reported.'
FROM RDB$DATABASE
UNION ALL SELECT 15, 'Audit, void, and reconciliation checks',
       'PAYMENT, PAYMENTDETAIL, COMMUNITYTAXCERTIFICATE, DELETE_AUDITTRAIL, HIS_AUDITTRAIL, T_STATUS',
       'VOID_BV, STATUS_CT, PAYMENT.AMOUNT, SUM(PAYMENTDETAIL.AMOUNTPAID), TOTALAMOUNTPAID, RECEIPTNO, CTCNO, DATALASTEDITED',
       'Reports should exclude voided receipts when appropriate and reconcile receipt amount, detail amount, and CTC certificate totals.'
FROM RDB$DATABASE
) flow
ORDER BY flow.STEP_NO;

/* 20. Process flow: Other Fees and Charges */
SELECT *
FROM (
SELECT 1 AS STEP_NO, 'Start from the transaction source' AS PROCESS_STEP,
       'BUSINESSPERMIT, BUSINESSPERMITDETAIL, BUSINESSPERMITJOURNAL, EEBILL, EECLEARANCE, EECITATION, WATERBILL, WATERBILLDETAIL, BURIALPERMIT, MARRIAGELICENSE, CATTLEOWNERSHIP, CATTLETRANSFER, MCHCHARGES, CASHTICKET' AS TABLES_INVOLVED,
       'Source primary key, LOCAL_TIN, application/bill/certificate dates, STATUS fields, USERID, TRANSDATE' AS IMPORTANT_FIELDS,
       'The originating office/module determines what the taxpayer is paying: business tax/permit, clearance, civil registry, animal/cattle fee, market/slaughter fee, water fee, environmental/economic enterprise charge, or other local fee.' AS WHAT_HAPPENS
FROM RDB$DATABASE
UNION ALL SELECT 2, 'Identify taxpayer or payor',
       'TAXPAYER, TAXPAYERDETAIL, source module tables, PAYMENT',
       'LOCAL_TIN, OWNERNAME, OWNERADDRESS, PAIDBY, CONTACT/DETAIL fields',
       'If the payor is registered, the transaction links through LOCAL_TIN. If not, the receipt may still store the payor name in PAYMENT.PAIDBY.'
FROM RDB$DATABASE
UNION ALL SELECT 3, 'Resolve revenue hierarchy',
       'T_ITAXTYPE',
       'CODE, DESCRIPTION, PARENTCODE, TREELEVEL, FUNDTYPE_CT, BLGF_CODE, COA_CODE',
       'The revenue code belongs to a parent-child hierarchy. Example: Local Sources -> Non-Tax Revenues -> Regulatory Fees -> Permits and Licenses -> Business Permit Fees -> Mayor''s Permit.'
FROM RDB$DATABASE
UNION ALL SELECT 4, 'Resolve rate or ordinance basis',
       'T_OTHERPAYMENTRATE, T_BPADDONCHARGES, T_BPCATEGORY, T_BPRATES, T_EERATE, T_MCHRATE, T_WATERITEM, T_WATERORDINANCE',
       'OPRATE_ID, ITAXTYPE_CT, RATE, YEARSTART, VALIDFROM, ORDINANCENO, module-specific rate/code fields',
       'The system determines the fee amount from general other-payment rates or from module-specific rate tables. Ordinance number and validity fields should be checked when auditing rate basis.'
FROM RDB$DATABASE
UNION ALL SELECT 5, 'Compute or encode assessed amount',
       'Source module tables, T_OTHERPAYMENTRATE, module rate tables',
       'AMOUNT, TAXDUE, TAXAMOUNT, SURCHARGE, INTEREST, RATE, UNIT, TOTALAMOUNT',
       'The source module may compute the collectible amount from rate, unit, gross sales, quantity, surcharge, interest, or manual encoded fee amount.'
FROM RDB$DATABASE
UNION ALL SELECT 6, 'Create official receipt header',
       'PAYMENT',
       'PAYMENT_ID, RECEIPTNO, PAYMENTDATE, VALUEDATE, LOCAL_TIN, PAIDBY, AMOUNT, PAYGROUP_CT, PAYMODE_CT, STATUS_CT, VOID_BV, COLLECTOR, USERID',
       'Cashier creates one PAYMENT row per official receipt. Other Fees and Charges are usually PAYGROUP_CT values such as OTH, TOB, EE, or blank, excluding RPT and CTC.'
FROM RDB$DATABASE
UNION ALL SELECT 7, 'Attach OR booklet and RCD references',
       'PAYMENT, RCDORBOOKLET, RCDORBOOKLETINVENTORY, RCDCTRLNUMBER',
       'RECEIPTNO, ORB_ID, RCDNUMBER, AFTYPE, STARTOR, ENDOR, LASTISSUEDOR, BOOKLETNO, COLLECTOR',
       'PAYMENT.RECEIPTNO stores the official receipt number. ORB_ID links to booklet control; RCDNUMBER links the collection to the Report of Collections and Deposits.'
FROM RDB$DATABASE
UNION ALL SELECT 8, 'Record fee line items',
       'PAYMENTDETAIL',
       'PAYMENTDETAIL_ID, PAYMENT_ID, ITAXTYPE_CT, FUNDTYPE_CT, SOURCE_CT, SOURCEID, UNIT, AMOUNTPAID, RECEIPTITEMORDER',
       'Each income item on the receipt is stored as a PAYMENTDETAIL row. This is the safest basis for collection totals because one receipt may contain multiple fee lines.'
FROM RDB$DATABASE
UNION ALL SELECT 9, 'Link line item to source transaction',
       'PAYMENTDETAIL plus source module tables',
       'SOURCE_CT, SOURCEID, PAYMENT_ID, module primary key fields',
       'SOURCE_CT and SOURCEID identify where the line came from. Observed source markers include PAY and module-specific identifiers; source tables should be checked when tracing an individual receipt.'
FROM RDB$DATABASE
UNION ALL SELECT 10, 'Record payment mode details if needed',
       'PAYMENTCHEQUE, T_PAYMODE, T_BANK',
       'CHEQUE_ID, PAYMENT_ID, BANKCODE, BRANCH, CHECKNUM, AMOUNT, VALUEDATE, CHEQUE_STATUS, PAYMODE_CT',
       'If payment is by cheque or another non-cash mode, supporting details are stored separately from the receipt header.'
FROM RDB$DATABASE
UNION ALL SELECT 11, 'Classify by fund and account',
       'PAYMENTDETAIL, T_ITAXTYPE, T_FUNDTYPE',
       'ITAXTYPE_CT, FUNDTYPE_CT, DESCRIPTION, BLGF_CODE, COA_CODE, AMOUNTPAID',
       'Collection reports group line amounts by revenue code and fund. T_ITAXTYPE supplies revenue description and account codes; T_FUNDTYPE supplies General Fund, Trust Fund, etc.'
FROM RDB$DATABASE
UNION ALL SELECT 12, 'Prepare cashier/RCD breakdown',
       'RCDCTRLNUMBER, RCDCASHBREAKDOWN, RCDFUNDTYPEBREAKDOWN, RCDACCOUNTABLEFORM',
       'RCDCTRL_ID, RCDNUMBER, RCDDATE, COLLECTOR, DENOMINATION, QUANTITY, GENERAL_FUND, SEF_FUND, TRUST_FUND, AMOUNT',
       'The cashier/accountable officer summarizes cash denomination, fund type totals, accountable forms, and RCD control details.'
FROM RDB$DATABASE
UNION ALL SELECT 13, 'Deposit / remittance control',
       'RCDDEPOSIT, REMITTANCE, BANKSTATEMENT, BANKSTATEMENTLINE',
       'DEPOSIT_ID, RCDNUMBER, DEPOSITDATE, BANKCODE_CT, AMOUNT, DEPOSIT_SLIP, REMIT_ID',
       'Deposit and remittance tables support bank/deposit reconciliation after collections are reported.'
FROM RDB$DATABASE
UNION ALL SELECT 14, 'Audit, void, and reconciliation checks',
       'PAYMENT, PAYMENTDETAIL, DELETE_AUDITTRAIL, HIS_AUDITTRAIL, T_STATUS',
       'VOID_BV, STATUS_CT, PAYMENT.AMOUNT, SUM(PAYMENTDETAIL.AMOUNTPAID), RECEIPTNO, DATALASTEDITED',
       'Reports should exclude voided receipts when appropriate. Reconcile PAYMENT.AMOUNT against SUM(PAYMENTDETAIL.AMOUNTPAID), and review audit tables for deleted or changed transactions.'
FROM RDB$DATABASE
) flow
ORDER BY flow.STEP_NO;
